apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: es-cluster
  labels:
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - port: 443
    targetPort: 9200  
  type: LoadBalancer