apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
  labels:
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 443
    targetPort: 9200  
    protocol: TCP
  type: LoadBalancer